# Generated by Django 4.0.5 on 2022-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_klasa_imazhi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klasa',
            old_name='pershkrimi',
            new_name='Ачыктоо',
        ),
        migrations.RenameField(
            model_name='klasa',
            old_name='titulli',
            new_name='Курстун_аты',
        ),
        migrations.RenameField(
            model_name='klasa',
            old_name='imazhi',
            new_name='Сурот',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='pershkrimi',
            new_name='Ачыктоо',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='klasa',
            new_name='Класс',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='titulli',
            new_name='Курстун_аты',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='imazhi_lendes',
            new_name='Сурот_туру',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pozicioni',
            new_name='Катары',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='titulli',
            new_name='Курстун_аты',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lenda',
            new_name='Туру',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Видео_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
