# Generated by Django 4.0.5 on 2022-06-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lesson_материалы'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Видео_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Видео',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Материалы',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
