# Generated by Django 4.0.5 on 2022-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_lesson_видео_id_lesson_видео_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Видео',
            field=models.FileField(default=0, upload_to='videos'),
        ),
    ]
